/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Main;

import javax.swing.JPanel;

/**
 *
 * @author argon
 */
public class ColourBlenderGUI extends javax.swing.JFrame {

    /**
     * Creates new form ColourBlenderGUI
     */
    public ColourBlenderGUI() {
        initComponents();
        ColourChooser1.setPreviewPanel(new JPanel());
        ColourChooser2.setPreviewPanel(new JPanel());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ColourChooser1 = new javax.swing.JColorChooser();
        BlendsSlider = new javax.swing.JSlider();
        Colour2Label = new javax.swing.JLabel();
        OutputSelector = new javax.swing.JComboBox<>();
        AmountLabel = new javax.swing.JLabel();
        BlendButton = new javax.swing.JButton();
        ColourChooser2 = new javax.swing.JColorChooser();
        Colour1Label = new javax.swing.JLabel();
        TitleLabel = new javax.swing.JLabel();
        OutputLabel = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        ColourPanel0 = new javax.swing.JPanel();
        ColourPanel1 = new javax.swing.JPanel();
        ColourPanel2 = new javax.swing.JPanel();
        ColourPanel3 = new javax.swing.JPanel();
        ColourPanel4 = new javax.swing.JPanel();
        ColourPanel5 = new javax.swing.JPanel();
        ColourPanel6 = new javax.swing.JPanel();
        ColourPanel7 = new javax.swing.JPanel();
        ColourPanel8 = new javax.swing.JPanel();
        ColourLabel0 = new javax.swing.JLabel();
        ColourLabel1 = new javax.swing.JLabel();
        ColourLabel2 = new javax.swing.JLabel();
        ColourLabel3 = new javax.swing.JLabel();
        ColourLabel4 = new javax.swing.JLabel();
        ColourLabel5 = new javax.swing.JLabel();
        ColourLabel6 = new javax.swing.JLabel();
        ColourLabel7 = new javax.swing.JLabel();
        ColourLabel8 = new javax.swing.JLabel();
        ColourCopy0 = new javax.swing.JButton();
        ColourCopy1 = new javax.swing.JButton();
        ColourCopy2 = new javax.swing.JButton();
        ColourCopy3 = new javax.swing.JButton();
        ColourCopy4 = new javax.swing.JButton();
        ColourCopy5 = new javax.swing.JButton();
        ColourCopy6 = new javax.swing.JButton();
        ColourCopy7 = new javax.swing.JButton();
        ColourCopy8 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        BlendsSlider.setMajorTickSpacing(1);
        BlendsSlider.setMaximum(7);
        BlendsSlider.setMinimum(1);
        BlendsSlider.setPaintLabels(true);
        BlendsSlider.setPaintTicks(true);
        BlendsSlider.setToolTipText("Amount of Blends");
        BlendsSlider.setName("Amount of Blends"); // NOI18N

        Colour2Label.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Colour2Label.setText("Colour #2");

        OutputSelector.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        OutputSelector.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Red Green Blue (RGB)", "HSV", "HSL", "HEX" }));

        AmountLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        AmountLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        AmountLabel.setText("Amount of Blends");

        BlendButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        BlendButton.setText("BLEND");
        BlendButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BlendButtonActionPerformed(evt);
            }
        });

        Colour1Label.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Colour1Label.setText("Colour #1");

        TitleLabel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        TitleLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        TitleLabel.setText("Colour Blender V1.0");

        OutputLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        OutputLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        OutputLabel.setText("Output Type");

        ColourPanel0.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        ColourPanel0.setMinimumSize(new java.awt.Dimension(99, 99));
        ColourPanel0.setPreferredSize(new java.awt.Dimension(99, 99));

        javax.swing.GroupLayout ColourPanel0Layout = new javax.swing.GroupLayout(ColourPanel0);
        ColourPanel0.setLayout(ColourPanel0Layout);
        ColourPanel0Layout.setHorizontalGroup(
            ColourPanel0Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 95, Short.MAX_VALUE)
        );
        ColourPanel0Layout.setVerticalGroup(
            ColourPanel0Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 95, Short.MAX_VALUE)
        );

        ColourPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        ColourPanel1.setMinimumSize(new java.awt.Dimension(99, 99));

        javax.swing.GroupLayout ColourPanel1Layout = new javax.swing.GroupLayout(ColourPanel1);
        ColourPanel1.setLayout(ColourPanel1Layout);
        ColourPanel1Layout.setHorizontalGroup(
            ColourPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 95, Short.MAX_VALUE)
        );
        ColourPanel1Layout.setVerticalGroup(
            ColourPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 95, Short.MAX_VALUE)
        );

        ColourPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        ColourPanel2.setMinimumSize(new java.awt.Dimension(99, 99));

        javax.swing.GroupLayout ColourPanel2Layout = new javax.swing.GroupLayout(ColourPanel2);
        ColourPanel2.setLayout(ColourPanel2Layout);
        ColourPanel2Layout.setHorizontalGroup(
            ColourPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 95, Short.MAX_VALUE)
        );
        ColourPanel2Layout.setVerticalGroup(
            ColourPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 95, Short.MAX_VALUE)
        );

        ColourPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        ColourPanel3.setMinimumSize(new java.awt.Dimension(99, 99));

        javax.swing.GroupLayout ColourPanel3Layout = new javax.swing.GroupLayout(ColourPanel3);
        ColourPanel3.setLayout(ColourPanel3Layout);
        ColourPanel3Layout.setHorizontalGroup(
            ColourPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 95, Short.MAX_VALUE)
        );
        ColourPanel3Layout.setVerticalGroup(
            ColourPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 95, Short.MAX_VALUE)
        );

        ColourPanel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        ColourPanel4.setMinimumSize(new java.awt.Dimension(99, 99));

        javax.swing.GroupLayout ColourPanel4Layout = new javax.swing.GroupLayout(ColourPanel4);
        ColourPanel4.setLayout(ColourPanel4Layout);
        ColourPanel4Layout.setHorizontalGroup(
            ColourPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 95, Short.MAX_VALUE)
        );
        ColourPanel4Layout.setVerticalGroup(
            ColourPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 95, Short.MAX_VALUE)
        );

        ColourPanel5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        ColourPanel5.setMinimumSize(new java.awt.Dimension(99, 99));

        javax.swing.GroupLayout ColourPanel5Layout = new javax.swing.GroupLayout(ColourPanel5);
        ColourPanel5.setLayout(ColourPanel5Layout);
        ColourPanel5Layout.setHorizontalGroup(
            ColourPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 95, Short.MAX_VALUE)
        );
        ColourPanel5Layout.setVerticalGroup(
            ColourPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 95, Short.MAX_VALUE)
        );

        ColourPanel6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        ColourPanel6.setMinimumSize(new java.awt.Dimension(99, 99));

        javax.swing.GroupLayout ColourPanel6Layout = new javax.swing.GroupLayout(ColourPanel6);
        ColourPanel6.setLayout(ColourPanel6Layout);
        ColourPanel6Layout.setHorizontalGroup(
            ColourPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 95, Short.MAX_VALUE)
        );
        ColourPanel6Layout.setVerticalGroup(
            ColourPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 95, Short.MAX_VALUE)
        );

        ColourPanel7.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        ColourPanel7.setMinimumSize(new java.awt.Dimension(99, 99));

        javax.swing.GroupLayout ColourPanel7Layout = new javax.swing.GroupLayout(ColourPanel7);
        ColourPanel7.setLayout(ColourPanel7Layout);
        ColourPanel7Layout.setHorizontalGroup(
            ColourPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 95, Short.MAX_VALUE)
        );
        ColourPanel7Layout.setVerticalGroup(
            ColourPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 95, Short.MAX_VALUE)
        );

        ColourPanel8.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        ColourPanel8.setMinimumSize(new java.awt.Dimension(99, 99));

        javax.swing.GroupLayout ColourPanel8Layout = new javax.swing.GroupLayout(ColourPanel8);
        ColourPanel8.setLayout(ColourPanel8Layout);
        ColourPanel8Layout.setHorizontalGroup(
            ColourPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 95, Short.MAX_VALUE)
        );
        ColourPanel8Layout.setVerticalGroup(
            ColourPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 95, Short.MAX_VALUE)
        );

        ColourLabel0.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ColourLabel0.setText("0");

        ColourLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ColourLabel1.setText("1");

        ColourLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ColourLabel2.setText("2");

        ColourLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ColourLabel3.setText("3");

        ColourLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ColourLabel4.setText("4");

        ColourLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ColourLabel5.setText("5");

        ColourLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ColourLabel6.setText("6");

        ColourLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ColourLabel7.setText("7");

        ColourLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ColourLabel8.setText("8");

        ColourCopy0.setText("Copy");

        ColourCopy1.setText("Copy");

        ColourCopy2.setText("Copy");
        ColourCopy2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ColourCopy2ActionPerformed(evt);
            }
        });

        ColourCopy3.setText("Copy");

        ColourCopy4.setText("Copy");

        ColourCopy5.setText("Copy");

        ColourCopy6.setText("Copy");

        ColourCopy7.setText("Copy");

        ColourCopy8.setText("Copy");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(513, 513, 513)
                        .addComponent(BlendButton, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(ColourLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(ColourPanel0, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(48, 48, 48)
                                .addComponent(ColourPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(ColourCopy0, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(ColourCopy1, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(48, 48, 48)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(ColourCopy2, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(ColourCopy3, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(ColourPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(48, 48, 48)
                                .addComponent(ColourPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(ColourLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(ColourLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(48, 48, 48)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(ColourPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ColourLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ColourCopy4, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(48, 48, 48)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(ColourCopy5, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(ColourCopy6, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(ColourPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(48, 48, 48)
                                .addComponent(ColourPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(ColourLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(ColourLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(48, 48, 48)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(ColourPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(48, 48, 48)
                                .addComponent(ColourPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(ColourLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(ColourLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(ColourCopy7, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(ColourCopy8, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TitleLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator1)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ColourChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 634, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Colour1Label))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(Colour2Label, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(ColourChooser2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(AmountLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(BlendsSlider, javax.swing.GroupLayout.DEFAULT_SIZE, 630, Short.MAX_VALUE))
                                .addGap(20, 20, 20)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(OutputSelector, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(OutputLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addComponent(jSeparator2))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ColourLabel0, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TitleLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Colour2Label)
                    .addComponent(Colour1Label))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ColourChooser2, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ColourChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AmountLabel)
                    .addComponent(OutputLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(BlendsSlider, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(OutputSelector))
                .addGap(12, 12, 12)
                .addComponent(BlendButton, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ColourPanel0, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ColourPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ColourPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ColourPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ColourPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ColourPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ColourPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ColourPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ColourPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ColourLabel0)
                    .addComponent(ColourLabel1)
                    .addComponent(ColourLabel2)
                    .addComponent(ColourLabel3)
                    .addComponent(ColourLabel4)
                    .addComponent(ColourLabel5)
                    .addComponent(ColourLabel6)
                    .addComponent(ColourLabel7)
                    .addComponent(ColourLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(ColourCopy0)
                        .addComponent(ColourCopy1))
                    .addComponent(ColourCopy2)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(ColourCopy4)
                        .addComponent(ColourCopy5)
                        .addComponent(ColourCopy6)
                        .addComponent(ColourCopy3)
                        .addComponent(ColourCopy7)
                        .addComponent(ColourCopy8)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BlendButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BlendButtonActionPerformed
        // TODO add your handling code here:
     
    }//GEN-LAST:event_BlendButtonActionPerformed

    private void ColourCopy2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ColourCopy2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ColourCopy2ActionPerformed

    /**
     * @param args the command line arguments
     */

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */

         
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ColourBlenderGUI.class.getName()).log(java.util.logging.Level.SEVERE,
                    null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ColourBlenderGUI.class.getName()).log(java.util.logging.Level.SEVERE,
                    null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ColourBlenderGUI.class.getName()).log(java.util.logging.Level.SEVERE,
                    null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ColourBlenderGUI.class.getName()).log(java.util.logging.Level.SEVERE,
                    null, ex);
        }
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ColourBlenderGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AmountLabel;
    private javax.swing.JButton BlendButton;
    private javax.swing.JSlider BlendsSlider;
    private javax.swing.JLabel Colour1Label;
    private javax.swing.JLabel Colour2Label;
    private javax.swing.JColorChooser ColourChooser1;
    private javax.swing.JColorChooser ColourChooser2;
    private javax.swing.JButton ColourCopy0;
    private javax.swing.JButton ColourCopy1;
    private javax.swing.JButton ColourCopy2;
    private javax.swing.JButton ColourCopy3;
    private javax.swing.JButton ColourCopy4;
    private javax.swing.JButton ColourCopy5;
    private javax.swing.JButton ColourCopy6;
    private javax.swing.JButton ColourCopy7;
    private javax.swing.JButton ColourCopy8;
    private javax.swing.JLabel ColourLabel0;
    private javax.swing.JLabel ColourLabel1;
    private javax.swing.JLabel ColourLabel2;
    private javax.swing.JLabel ColourLabel3;
    private javax.swing.JLabel ColourLabel4;
    private javax.swing.JLabel ColourLabel5;
    private javax.swing.JLabel ColourLabel6;
    private javax.swing.JLabel ColourLabel7;
    private javax.swing.JLabel ColourLabel8;
    private javax.swing.JPanel ColourPanel0;
    private javax.swing.JPanel ColourPanel1;
    private javax.swing.JPanel ColourPanel2;
    private javax.swing.JPanel ColourPanel3;
    private javax.swing.JPanel ColourPanel4;
    private javax.swing.JPanel ColourPanel5;
    private javax.swing.JPanel ColourPanel6;
    private javax.swing.JPanel ColourPanel7;
    private javax.swing.JPanel ColourPanel8;
    private javax.swing.JLabel OutputLabel;
    private javax.swing.JComboBox<String> OutputSelector;
    private javax.swing.JLabel TitleLabel;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    // End of variables declaration//GEN-END:variables
}
